# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - "*"

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    env
    echo "SourceBranch: $(Build.SourceBranch)"
    echo "SourceBranchName: $(Build.SourceBranchName)"
    echo "- Pull Request info -"
    echo "PullRequestId: $(System.PullRequest.PullRequestId)"
    echo "PullRequestNumber: $(System.PullRequest.PullRequestNumber)"
    echo "SourceBranch: $(System.PullRequest.SourceBranch)"
    echo "TargetBranch: $(System.PullRequest.TargetBranch)"
  displayName: Echo vars
